mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # #ex /polls/
    path('', views.index, name = 'index'),
    # path('', views.IndexView.as_view(), name = 'index'),

    # #ex /polls/5/
    path('<int:question_id>/', views.detail, name='detail' ),
    # path('<int:pk>/',views.DetailView.as_view(), name= 'detail'),
    #클래스를 호출하는 경우 question_id를 불러오는게 아니라 pk를 불러옴

    # #ex /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # path('<int:pk>/result',views.ResultView.as_view(), name= 'results'),

    # #ex /polls/5/vote/
    path('<int:question_id>/vote', views.vote, name= 'vote'),

    path('login/', views.loginview, name='login'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'  # pub_date로 정렬하겠다
    was_published_recently.boolean = True  # 아이콘 모양으로 바꿔줌
    was_published_recently.short_description = "Published recently?"  # 타이틀 변경


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Acount_Login(models.Model):
    IDwlgns = models.CharField(max_length= 20, primary_key=True, unique=True)
    passwordwlgns = models.CharField(max_length= 20)

    def __str__(self):
        return self.userid

polls/views.py
"""
views.py의 가장 큰 역할은 request 를 받고 response를 해주는 역할이다.

"""
import datetime
from re import template

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.models import User
from io import StringIO
import requests
import json

from .models import Question, Choice, Acount_Login


def index(request):
    # 1. base view
    # return HttpResponse("hello world. youre at the polls index.")

    # 2. Actually do something
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # output = ', '.join([q.question_text for q in latest_question_list])
    # return HttpResponse(output)

    # 3. Use the template
    # lastest_question_list = Question.objects.order_by('-pub_date')[:5]
    # context = {'latest_question_list' : lastest_question_list}
    # return render(request, 'polls/index.html',context)

    # 4 Using the shortcut - render
    if request.method == "GET":
        latest_question_list = Question.objects.order_by('-pub_date')[:5]
        template = loader.get_template('polls/index.html')
        context = {
            'latest_question_list': latest_question_list,
        }
        return HttpResponse(template.render(context, request))

    if request.method == "POST":
        if request.POST['questionname']:  # html 안에 name를 전달받음.ㅎㅎ
            Question.objects.create(question_text=request.POST['questionname'], pub_date=datetime.datetime.now())
            print("Success")
        return HttpResponseRedirect('/polls')


# class IndexView(generic.ListView):
#     template_name = 'polls/index.html'
#     context_object_name = 'latest_question_list'

#     def get_queryset(self):
#         return Question.objects.filter(
#             pub_date__lte=timezone.now() #lte는 less than equal
#         ).order_by('-pub_date')[:5]


def detail(request, question_id):
    #     #1
    #     #  try:
    #     #     question = Question.objects.get(pk=question_id)
    #     # except Question.DoesNotExist:
    #     #     raise Http404("Question does not exist")
    #     # return render(request, 'polls/detail.html',{'question':question})

    #     #2
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


# class DetailView(generic.DetailView):
#     model = Question
#     template_name = "polls/detail.html"

#     def get_queryset(self):
#         return Question.objects.filter(pub_date__lte=timezone.now())


def results(request, question_id):
    #     # 1.
    # return HttpResponse("You're looking at the results of question %s" % question_id)
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


# class ResultView(DetailView):
#     model = Question
#     template_name = "polls/results.html"


def vote(request, question_id):
    # 1.
    #  return HttpResponse("You're voting on quesetion %s" % question_id)

    # 2.
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(
            question.id,)))  # post 로 호출된 경우어는 HttpResponesREdirect 로 리턴해준다. reserve는 뷰 함수에서 URL을 하드코딩하지 않게 해준다.


def loginview(request):
    if request.method == "POST":
        if request.POST['username']:  # html 안에 name을 전달받음.ㅎㅎ
            loginData = {
                "loginId": request.POST['username'],
                "password": request.POST['password'],
            }
            LoginRequest = requests.post(url="https://oasis.ssu.ac.kr/pyxis-api/api/login", json=loginData)

            AccessToken = json.load(StringIO(LoginRequest.text))['data']['accessToken']
            print(AccessToken)
            Info =requests.get(url= "https://oasis.ssu.ac.kr/pyxis-api/1/popular-charged-books?max=100&durationMonth=&month=202107", headers={"pyxis-auth-token":AccessToken})

            if LoginRequest:
                return HttpResponse(Info.text)
            else:
                return HttpResponse('fail')
        else:
            return HttpResponse("fail")

    else:
        # latest_user_list = Login.objects.order_by('username')[:5]
        template = loader.get_template('polls/login.html')
        context = {

        }
        return HttpResponse(template.render(context, request))

polls/templates/polls/detail.html
{% comment %} <h1>{{ question.question_text}}</h1> {% endcomment %}

{% comment %} <ul>
    {%for choice in question.choice_set.all %}
        <li> {{ choice.choice_text }} </li>
    {%endfor%}
</ul> {% endcomment %}


{%if error_message %}<p>{{ error_message }}</p>>{% endif %}


<form action="{% url 'polls:vote' question.id %}" method="post" >
    {%csrf_token %} <!-- 해킹방지를 위해 넣어놓음 form 태그 안에는 넣어놓는다-->
    <fieldset>
        <legend><h1>{{question.question_text}}</h1></legend>
        {%if error_message %} <p><strong>{{ error_message }}</strong></p>{%endif%}


        {%for choice in question.choice_set.all%}
            <input type="radio" name="choice" id="choice{{forloop.counter }}" value="{{choice.id}}">
            <label for="choice{{ forloop.counter }}"> {{choice.choice_text}}</label><br> <!--forloop.counter는 for문이 반복한 횟수를 나타낸다-->
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load  static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">


{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}"> {{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}



<form action="/polls/" method="post" enctype="multipart/form-data">
    {% csrf_token %} <!-- 해킹방지를 위해 넣어놓음 form 태그 안에는 넣어놓는다-->
    <input id="questionid" type="text" name="questionname">
    <input type="submit" value="질문 추가">
</form>

polls/templates/polls/login.html
<form method="post" action="{% url 'polls:login' %}">
    {% csrf_token %}
    <label for="username"> id put</label>
    <input type="text"  name="username" id="username">
    <label for="password">password</label>
    <input type="password" name="password" id="password">
    <button type="submit">login</button>
</form>


{#{% if latest_question_list %}#}
{#    <ul>#}
{#        {% for question in latest_question_list %}#}
{#            <li><a href="{% url 'polls:detail' question.id %}"> {{ question.question_text }}</a></li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#{% else %}#}
{#    <p>No user are available.</p>#}
{#{% endif %}#}

polls/templates/polls/results.html
<h1> {{ question.question_text }}</h1>

<ul>
{%for choice in question.choice_set.all %}
    <li> {{ choice.choice_text }} -- {{ choice.votes }}
vote{{ choice.votes|pluralize}} </li>
{%endfor%}
</ul>

<a href="{% url 'polls:vote' question.id %}"> Vote again </a>